TWITTER_CLIENT_ID = '4kQ2lYO4QbTPYzlktumoypPZX'
TWITTER_CLIENT_SECRET = 'Of6038YMKPgVvKFjaMfU5lJa9ASK9kLTK7VjNlOOxF8iSOn0Z3'
REGISTERED_USERS_SAVE = 'OAUTHUsers.pickle'
SESSIONS_SAVE = 'sessions.pickle'